theme: jekyll-theme-minimal
title: Baylor Blackmarket Bookstore
description: This site helps baylor students buy and sell textbooks with ease
logo: https://a2.espncdn.com/combiner/i?img=%2Fi%2Fteamlogos%2Fncaa%2F500%2F239.png
